language: c
script: 
  - cd xdelta3 
  - buildXDelta.sh # build as static library
  - make clean # cleanup static library build artefacts
  - autoreconf --install &&  ./configure --disable-dependency-tracking && make # build as executable
compiler: gcc