language: c
script: 
  - ./xdelta3/buildXDelta.sh # build as static library
  - cd xdelta3 && autoreconf --install &&  ./configure --disable-dependency-tracking && make # build as executable
compiler: gcc